/* diff.mjs — scene diffing for review.
 * Compares two blueprint scenes (before/after) and produces a merged diff
 * scene: nodes and edges carry `delta` (added|removed|changed) plus a
 * human-readable `changes` list. The renderer draws the delta vocabulary
 * (+ badge, hollow diamond, ghost) and offers a changed-only filter.
 */

const NODE_FIELDS = ["label", "status", "shape", "summary", "does", "built", "condition"];

function indexBy(list, key) {
  const m = new Map();
  for (const item of list || []) m.set(typeof key === "function" ? key(item) : item[key], item);
  return m;
}

export function diffScenes(before, after) {
  const aN = indexBy(before.nodes, "id");
  const bN = indexBy(after.nodes, "id");
  const nodes = [];
  let added = 0, removed = 0, changed = 0;

  for (const [id, b] of bN) {
    const a = aN.get(id);
    if (!a) {
      nodes.push(Object.assign({}, b, { delta: "added" }));
      added++;
      continue;
    }
    const changes = [];
    for (const f of NODE_FIELDS) {
      if ((a[f] || "") !== (b[f] || "")) {
        changes.push(f === "status" ? `status: ${a.status || "built"} → ${b.status || "built"}` : `${f} changed`);
      }
    }
    nodes.push(Object.assign({}, b, changes.length ? { delta: "changed", changes } : {}));
    if (changes.length) changed++;
  }
  for (const [id, a] of aN) {
    if (!bN.has(id)) {
      nodes.push(Object.assign({}, a, { delta: "removed" }));
      removed++;
    }
  }

  const edgeKey = (e) => `${e.from}>${e.to}`;
  const aE = indexBy(before.edges, edgeKey);
  const bE = indexBy(after.edges, edgeKey);
  const edges = [];
  for (const [k, b] of bE) {
    const a = aE.get(k);
    if (!a) edges.push(Object.assign({}, b, { delta: "added" }));
    else if ((a.label || "") !== (b.label || "") || (a.status || "built") !== (b.status || "built")) {
      edges.push(Object.assign({}, b, { delta: "changed", changes: ["wire changed"] }));
    } else edges.push(b);
  }
  for (const [k, a] of aE) {
    if (!bE.has(k)) edges.push(Object.assign({}, a, { delta: "removed" }));
  }

  const parts = [];
  if (added) parts.push(`==${added} added==`);
  if (removed) parts.push(`==${removed} removed==`);
  if (changed) parts.push(`==${changed} changed==`);
  if (!parts.length) parts.push("no structural changes");
  const bullets = nodes
    .filter((n) => n.delta)
    .slice(0, 30)
    .map((n) => `- [${n.id}] ${n.label || n.id} — ${n.delta}${n.changes ? ": " + n.changes.join(", ") : ""}`);

  const name = after.title || before.title || "blueprint";
  return {
    title: name,
    subtitle: "diff",
    legendTitle: "the diff",
    heading: `${name} — before / after`,
    tagline: parts.join(" · ").replace(/==/g, ""),
    description: `This scene is a ==diff==. ${parts.join(" · ")}.\n\n${bullets.join("\n")}\n\nToggle ==changed only== in the header to hide untouched structures. Ghosted blocks were removed; ` +
      "`+` badges are new; hollow diamonds changed.",
    built: "Generated by ==blueprint diff==. Nodes and wires carry a delta; the rest of the scene is context.",
    groups: after.groups || before.groups,
    regions: after.regions || before.regions,
    nodes,
    edges,
    flow: (after.flow || before.flow || []).filter((id) => bN.has(id)),
    _hasDelta: true,
  };
}

/* bp:node DIFF "scene diff" group:engines
 * bp:does Merges before/after scenes into one ==delta scene==: added, removed, changed, untouched.
 * bp:built src/diff.mjs — diffScenes(); edges keyed from>to; nodes carry a changes list.
 * bp:edge DIFF -> SCAN : rescans at git ref
 */
